return {
  { "folke/trouble.nvim", opts = { use_diagnostic_signs = true } },
  { "tpope/vim-fugitive", enabled = true },
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = { "LazyFile", "VeryLazy" },
    opts = {
      highlight = {
        enable = true,
      },
      indent = { enable = true },
      ensure_installed = {
        "bash",
        "c",
        "css",
        "diff",
        "dockerfile",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "html",
        "jsdoc",
        "json",
        "json5",
        "jsonc",
        "just",
        "latex",
        "lua",
        "luadoc",
        "luap",
        "make",
        "markdown",
        "markdown_inline",
        "mermaid",
        "ninja",
        "norg",
        "printf",
        "proto",
        "python",
        "query",
        "regex",
        "requirements",
        "ron",
        "rst",
        "rust",
        "scss",
        "sql",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "xml",
        "zig",
      },
    },
  },
}
